In [ ]:
#Numpy - Numerical Python

#Array
#1d array - called as vector - List
#2d array - called as matrix - list of lists

In [1]:
import numpy as np

In [2]:
sample_list = [100,101,102,103]

In [3]:
print(sample_list)

[100, 101, 102, 103]


In [4]:
type(sample_list)

list

In [11]:
#1d array
sample_array = np.array(sample_list)

In [12]:
print(sample_array)

[100 101 102 103]


In [9]:
type(sample_array)

numpy.ndarray

In [10]:
sample_array.size

4

In [13]:
customer_info_list_of_lists = [["515154521564", "John", 45, 15000,"Married"],["456145654","David",34,8000,"Married"],["2121211","Annie",32,5465,"Unmarried"]]#2D

In [14]:
customer_info_list_of_lists

[['515154521564', 'John', 45, 15000, 'Married'],
 ['456145654', 'David', 34, 8000, 'Married'],
 ['2121211', 'Annie', 32, 5465, 'Unmarried']]

In [15]:
#2d array
np.array(customer_info_list_of_lists)

array([['515154521564', 'John', '45', '15000', 'Married'],
       ['456145654', 'David', '34', '8000', 'Married'],
       ['2121211', 'Annie', '32', '5465', 'Unmarried']], dtype='<U12')

In [16]:
#3d array
list_of_list_of_lists = [[[10,20,30,40],[50,60,70,80],[90,100,110,120],[130,140,160,200]],[[45,20,30,40],[50,75,70,80],[90,150,110,120],[130,140,160,200]]]
np.array(list_of_list_of_lists)

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120],
        [130, 140, 160, 200]],

       [[ 45,  20,  30,  40],
        [ 50,  75,  70,  80],
        [ 90, 150, 110, 120],
        [130, 140, 160, 200]]])

In [17]:
import pandas as pd
car_df = pd.read_csv("car-mpg.csv")

In [18]:
np.array(car_df)

array([[18.0, 8, 307.0, ..., 1, 0, 'chevrolet chevelle malibu'],
       [15.0, 8, 350.0, ..., 1, 0, 'buick skylark 320'],
       [18.0, 8, 318.0, ..., 1, 0, 'plymouth satellite'],
       ...,
       [32.0, 4, 135.0, ..., 1, 1, 'dodge rampage'],
       [28.0, 4, 120.0, ..., 1, 1, 'ford ranger'],
       [31.0, 4, 119.0, ..., 1, 1, 'chevy s-10']], dtype=object)

In [19]:
car_df

mpg  cyl   disp   hp    wt   acc  yr  origin  car_type  \
0    18.0    8  307.0  130  3504  12.0  70       1         0   
1    15.0    8  350.0  165  3693  11.5  70       1         0   
2    18.0    8  318.0  150  3436  11.0  70       1         0   
3    16.0    8  304.0  150  3433  12.0  70       1         0   
4    17.0    8  302.0  140  3449  10.5  70       1         0   
..    ...  ...    ...  ...   ...   ...  ..     ...       ...   
393  27.0    4  140.0   86  2790  15.6  82       1         1   
394  44.0    4   97.0   52  2130  24.6  82       2         1   
395  32.0    4  135.0   84  2295  11.6  82       1         1   
396  28.0    4  120.0   79  2625  18.6  82       1         1   
397  31.0    4  119.0   82  2720  19.4  82       1         1   

                      car_name  
0    chevrolet chevelle malibu  
1            buick skylark 320  
2           plymouth satellite  
3                amc rebel sst  
4                  ford torino  
..                         ...  
393            ford mustang gl  
394                  vw pickup  
395              dodge rampage  
396                ford ranger  
397                 chevy s-10  

[398 rows x 10 columns]

arange

In [21]:
np.arange(0,100,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [24]:
np.arange(start=0,stop=100,step=10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
np.arange(0.2532,0.95555,0.1)

array([0.2532, 0.3532, 0.4532, 0.5532, 0.6532, 0.7532, 0.8532, 0.9532])

zeros

In [26]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

ones

In [35]:
np.ones(30)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
np.ones((4,5,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

linspace

In [34]:
np.linspace(start=1,stop=100,num=50,endpoint=True)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

eye

In [35]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

Random

In [36]:
np.random.rand(100)#uniform distribution between 0 and 1

array([0.49387991, 0.97615356, 0.60816396, 0.81869935, 0.56304443,
       0.1368102 , 0.98191186, 0.81330311, 0.72039603, 0.60377826,
       0.0477177 , 0.46971002, 0.57111031, 0.68525426, 0.50973732,
       0.10441452, 0.97101866, 0.94257107, 0.68246729, 0.40623932,
       0.56721781, 0.84597429, 0.62351478, 0.09652814, 0.913812  ,
       0.54285479, 0.25478505, 0.4385645 , 0.895089  , 0.86891315,
       0.43898314, 0.1215088 , 0.9942327 , 0.21433045, 0.51673529,
       0.03469825, 0.76725425, 0.3234193 , 0.98027383, 0.47347269,
       0.77540024, 0.92402894, 0.41283282, 0.81001664, 0.03897726,
       0.03258184, 0.38750576, 0.16567181, 0.68202827, 0.16247534,
       0.93171443, 0.3946704 , 0.66748321, 0.20350821, 0.49565814,
       0.58149714, 0.02729476, 0.57734353, 0.7587991 , 0.83852862,
       0.15899296, 0.0018148 , 0.3225569 , 0.05135548, 0.46022451,
       0.5283773 , 0.35696421, 0.68474509, 0.12474111, 0.58480456,
       0.12431619, 0.72285325, 0.78789399, 0.75253716, 0.68373

In [52]:
np.random.randn(5)#standard normal distribution

array([-0.36163234, -0.5459453 ,  1.03449773,  0.2861094 , -0.99825789])

In [53]:
np.sort(np.random.randn(5))

array([-0.90266788, -0.61697289, -0.09272348,  0.44311161,  1.73896079])

In [55]:
np.random.uniform(1000,2000,15)

array([1023.12056854, 1809.23466121, 1058.00897423, 1867.78314262,
       1005.42965078, 1204.36006321, 1949.8084059 , 1035.4590372 ,
       1057.71869389, 1505.41254857, 1227.06769841, 1063.09753014,
       1535.45267236, 1300.04633531, 1830.39051302])

In [50]:
np.random.randint(100,200,10)

array([152, 134, 113, 188, 122, 177, 115, 180, 149, 170])

In [109]:
np.random.randint(10)

1

Array Methods and Attributes

In [113]:
sample_array = np.arange(20)

In [115]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
sample_array.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [117]:
sample_array.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [71]:
sample_array.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [72]:
sample_array.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [73]:
sample_array.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [74]:
sample_array.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [118]:
sample_array1 = np.arange(30)
sample_array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [119]:
sample_array1.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [120]:
sample_array1.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [121]:
sample_array1.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [122]:
sample_array1.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [81]:
sample_array1.reshape(3,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [133]:
sample_array = np.random.randint(100,2000,10)
sample_array

array([ 927, 1332, 1269,  229, 1610,  635, 1961,  223,  827,  944])

In [134]:
sample_array.max()

1961

In [135]:
sample_array.min()

223

In [136]:
sample_array.mean()

995.7

In [137]:
sample_array.std()#standard deviation

533.6487702599904

In [138]:
sample_array.shape

(10,)

In [139]:
sample_array = np.random.randn(5,5)
sample_array

array([[ 0.63549975,  0.91474678,  0.05741185, -0.52632401, -0.05118459],
       [ 0.2465152 , -0.00225931,  0.05474776,  0.03714016,  1.16440411],
       [ 0.96293905,  0.08894687, -0.67658029, -0.99633419, -0.36699471],
       [ 1.81904841, -0.07248859, -0.96732136,  0.87359592,  1.92723795],
       [-1.14814744,  1.10335717,  0.7640774 , -0.31500611,  0.49324677]])

In [103]:
sample_array.shape

(5, 5)

In [140]:
#Transposing a Matrix
sample_array

array([[ 0.63549975,  0.91474678,  0.05741185, -0.52632401, -0.05118459],
       [ 0.2465152 , -0.00225931,  0.05474776,  0.03714016,  1.16440411],
       [ 0.96293905,  0.08894687, -0.67658029, -0.99633419, -0.36699471],
       [ 1.81904841, -0.07248859, -0.96732136,  0.87359592,  1.92723795],
       [-1.14814744,  1.10335717,  0.7640774 , -0.31500611,  0.49324677]])

In [141]:
sample_array.T

array([[ 0.63549975,  0.2465152 ,  0.96293905,  1.81904841, -1.14814744],
       [ 0.91474678, -0.00225931,  0.08894687, -0.07248859,  1.10335717],
       [ 0.05741185,  0.05474776, -0.67658029, -0.96732136,  0.7640774 ],
       [-0.52632401,  0.03714016, -0.99633419,  0.87359592, -0.31500611],
       [-0.05118459,  1.16440411, -0.36699471,  1.92723795,  0.49324677]])

In [107]:
np.random.randn(5,3).T

array([[-0.44178228, -0.60371299, -0.99373297, -1.86811271,  2.07615984],
       [ 0.77273375,  1.50942307, -0.41415334, -0.43009968, -0.06656936],
       [-0.83510137, -1.41125105, -1.31156777, -0.61055204, -0.268995  ]])

In [143]:
#Indexing and Selection
simple_array = np.arange(10,31)
simple_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [144]:
simple_array.shape

(21,)

In [146]:
#Indexing
simple_array[9]

19

In [148]:
#Range Selection
simple_array[12:17]

array([22, 23, 24, 25, 26])

In [149]:
#Specific Indexing
simple_array[[3,7,12]]

array([13, 17, 22])

In [150]:
#Indexing a matrix
sample_array

array([[ 0.63549975,  0.91474678,  0.05741185, -0.52632401, -0.05118459],
       [ 0.2465152 , -0.00225931,  0.05474776,  0.03714016,  1.16440411],
       [ 0.96293905,  0.08894687, -0.67658029, -0.99633419, -0.36699471],
       [ 1.81904841, -0.07248859, -0.96732136,  0.87359592,  1.92723795],
       [-1.14814744,  1.10335717,  0.7640774 , -0.31500611,  0.49324677]])

In [151]:
sample_array[0]

array([ 0.63549975,  0.91474678,  0.05741185, -0.52632401, -0.05118459])

In [152]:
sample_array[4]

array([-1.14814744,  1.10335717,  0.7640774 , -0.31500611,  0.49324677])

In [153]:
sample_array[2][2]

-0.6765802929862251

In [155]:
sample_array[3][3]

0.8735959221406281

In [156]:
sample_array[3][1]

-0.07248858907433361

In [157]:
sample_array

array([[ 0.63549975,  0.91474678,  0.05741185, -0.52632401, -0.05118459],
       [ 0.2465152 , -0.00225931,  0.05474776,  0.03714016,  1.16440411],
       [ 0.96293905,  0.08894687, -0.67658029, -0.99633419, -0.36699471],
       [ 1.81904841, -0.07248859, -0.96732136,  0.87359592,  1.92723795],
       [-1.14814744,  1.10335717,  0.7640774 , -0.31500611,  0.49324677]])

In [158]:
#Slicing
#-0.67658029, -0.99633419
#-0.96732136,  0.87359592
sample_array[2:4,2:4]

array([[-0.67658029, -0.99633419],
       [-0.96732136,  0.87359592]])

In [159]:
#-0.00225931,  0.05474776,  0.03714016
# 0.08894687, -0.67658029, -0.99633419
sample_array[1:3,1:4]

array([[-0.00225931,  0.05474776,  0.03714016],
       [ 0.08894687, -0.67658029, -0.99633419]])

In [160]:
#1.81904841, -0.07248859
#-1.14814744,  1.10335717
sample_array[3:5,0:2]

array([[ 1.81904841, -0.07248859],
       [-1.14814744,  1.10335717]])

In [137]:
#Arithmetic Operations

In [161]:
employee_salary_1d_jan = np.random.randint(10000,20000,100)
employee_salary_1d_feb = np.random.randint(10000,20000,100)

In [163]:
employee_salary_1d_jan

array([13275, 13161, 11586, 11809, 19642, 13786, 19074, 14497, 19525,
       15121, 11723, 12353, 17120, 12462, 10972, 13227, 16758, 16366,
       14397, 15930, 19614, 11163, 15826, 17554, 17805, 19864, 16447,
       16194, 18074, 19911, 14199, 13791, 15700, 16661, 13180, 15178,
       12738, 14973, 15799, 16682, 12220, 12656, 11921, 16083, 16739,
       17393, 13682, 10447, 17390, 10055, 17686, 12138, 10028, 16837,
       11992, 10832, 17341, 14302, 18905, 14410, 10236, 14535, 19463,
       17847, 17198, 17291, 18677, 14270, 12624, 17925, 13029, 12089,
       19835, 18175, 11593, 13790, 11402, 14126, 11169, 13609, 19434,
       18746, 11661, 17950, 17920, 11730, 11330, 18235, 19400, 15320,
       12532, 16054, 14530, 16221, 12892, 13332, 16252, 14853, 10804,
       19019])

In [164]:
employee_salary_1d_feb

array([15422, 16416, 15913, 14119, 10319, 13366, 14809, 11993, 19027,
       16959, 19315, 10678, 12486, 15734, 18712, 14567, 14541, 19986,
       18933, 17482, 10669, 11550, 12617, 14887, 10260, 17739, 11917,
       11611, 14292, 17936, 18150, 12807, 14794, 17008, 12154, 17892,
       14110, 14196, 13030, 12349, 13310, 10800, 11389, 11609, 11607,
       12534, 16097, 10433, 11310, 14481, 10032, 16695, 18288, 14403,
       16081, 12230, 10375, 13931, 17056, 10079, 11789, 16830, 18606,
       15357, 12414, 17537, 12818, 16187, 17486, 13399, 13815, 12438,
       13095, 16843, 11360, 13443, 16427, 10021, 13029, 12354, 17965,
       19351, 13187, 16583, 10638, 13578, 19033, 12190, 10783, 14767,
       15104, 15158, 11585, 12975, 13252, 11688, 18439, 14112, 12764,
       16690])

In [165]:
employee_salary_1d_jan + employee_salary_1d_feb

array([28697, 29577, 27499, 25928, 29961, 27152, 33883, 26490, 38552,
       32080, 31038, 23031, 29606, 28196, 29684, 27794, 31299, 36352,
       33330, 33412, 30283, 22713, 28443, 32441, 28065, 37603, 28364,
       27805, 32366, 37847, 32349, 26598, 30494, 33669, 25334, 33070,
       26848, 29169, 28829, 29031, 25530, 23456, 23310, 27692, 28346,
       29927, 29779, 20880, 28700, 24536, 27718, 28833, 28316, 31240,
       28073, 23062, 27716, 28233, 35961, 24489, 22025, 31365, 38069,
       33204, 29612, 34828, 31495, 30457, 30110, 31324, 26844, 24527,
       32930, 35018, 22953, 27233, 27829, 24147, 24198, 25963, 37399,
       38097, 24848, 34533, 28558, 25308, 30363, 30425, 30183, 30087,
       27636, 31212, 26115, 29196, 26144, 25020, 34691, 28965, 23568,
       35709])

In [155]:
employee_salary_1d_jan * employee_salary_1d_feb

array([145020774, 135513323, 206418432, 125488275, 193984044, 208399107,
       237453942, 278654820, 237994407, 166597704, 323677527, 256700315,
       315262335, 190329048, 118018516, 220313010, 333683973, 233558112,
       362838915, 233593740, 245681584, 171933003, 277585325, 308430372,
       211131738, 142111542, 172913373, 236673984, 236298140, 243394585,
       253068624, 234046160, 199448275, 175887471, 252432969, 381281446,
       377194390, 223112974, 278514636, 285817116, 308500080, 164920332,
       238471964, 300333474, 216229923, 267099120, 214300320, 185506548,
       302032080, 222779210, 294294979, 163440088, 150922000, 264851930,
       222816501, 243828080, 242916528, 302174100, 125251808, 254441088,
       167529180, 233077905, 353799695, 241014410, 238524399, 276238707,
       354129600, 269414444, 151322976, 200013363, 293731200, 252060312,
       186293580, 152499752, 120119460, 186799968, 266008476, 211757162,
       214897293, 119002598, 210421622, 301753050, 

In [167]:
#Universal Array Functions for Mathematical Operations
sample_array_sqrd = np.square(sample_array)

In [168]:
sample_array_sqrd

array([[4.03859932e-01, 8.36761670e-01, 3.29612015e-03, 2.77016961e-01,
        2.61986274e-03],
       [6.07697457e-02, 5.10446993e-06, 2.99731768e-03, 1.37939132e-03,
        1.35583694e+00],
       [9.27251621e-01, 7.91154537e-03, 4.57760893e-01, 9.92681817e-01,
        1.34685118e-01],
       [3.30893713e+00, 5.25459555e-03, 9.35710623e-01, 7.63169835e-01,
        3.71424611e+00],
       [1.31824254e+00, 1.21739705e+00, 5.83814277e-01, 9.92288492e-02,
        2.43292377e-01]])

In [169]:
sample_array

array([[ 0.63549975,  0.91474678,  0.05741185, -0.52632401, -0.05118459],
       [ 0.2465152 , -0.00225931,  0.05474776,  0.03714016,  1.16440411],
       [ 0.96293905,  0.08894687, -0.67658029, -0.99633419, -0.36699471],
       [ 1.81904841, -0.07248859, -0.96732136,  0.87359592,  1.92723795],
       [-1.14814744,  1.10335717,  0.7640774 , -0.31500611,  0.49324677]])

In [170]:
np.sqrt(sample_array_sqrd)

array([[0.63549975, 0.91474678, 0.05741185, 0.52632401, 0.05118459],
       [0.2465152 , 0.00225931, 0.05474776, 0.03714016, 1.16440411],
       [0.96293905, 0.08894687, 0.67658029, 0.99633419, 0.36699471],
       [1.81904841, 0.07248859, 0.96732136, 0.87359592, 1.92723795],
       [1.14814744, 1.10335717, 0.7640774 , 0.31500611, 0.49324677]])

In [172]:
np.min(sample_array_sqrd)

5.104469925372994e-06

In [164]:
np.max(sample_array_sqrd)

4.472841047432626

In [165]:
np.sin(sample_array_sqrd)

array([[ 0.48628834,  0.75468154,  0.87152095,  0.93371945,  0.16782358],
       [ 0.0073663 ,  0.90176927,  0.92021702,  0.82900391,  0.17959094],
       [ 0.21293442,  0.00911084,  0.68096895, -0.97144533,  0.43484512],
       [ 0.11022505,  0.0293882 ,  0.11910926, -0.53562603,  0.79586345],
       [ 0.77014256,  0.06216584,  0.77546004,  0.10625133,  0.1676979 ]])

In [166]:
np.cos(sample_array_sqrd)

array([[ 0.87379841,  0.65609129,  0.49035826,  0.35800556,  0.98581705],
       [ 0.99997287,  0.43221776,  0.39140852,  0.55924281,  0.98374138],
       [ 0.97706649,  0.9999585 , -0.73231229, -0.23726349, -0.90050526],
       [ 0.99390666,  0.99956807,  0.99288115, -0.8444553 ,  0.60547615],
       [ 0.63787181,  0.99806583,  0.63139665,  0.99433931,  0.98583843]])

In [168]:
np.tan(sample_array_sqrd)

array([[ 0.55652234,  1.15026911,  1.77731471,  2.60811436,  0.17023806],
       [ 0.0073665 ,  2.08637718,  2.35103984,  1.48236846,  0.1825591 ],
       [ 0.21793237,  0.00911122, -0.92988874,  4.09437341, -0.48289016],
       [ 0.1109008 ,  0.0294009 ,  0.11996326,  0.63428583,  1.31444226],
       [ 1.20736259,  0.06228631,  1.22816623,  0.10685621,  0.17010688]])

In [169]:
np.log(sample_array_sqrd)

array([[-0.6775948 , -0.15645665,  0.05665964,  0.18620179, -1.78009862],
       [-4.9108313 ,  0.11675642,  0.15583605, -0.02293687, -1.71163336],
       [-1.53908535, -4.69827649,  0.87234206,  1.49802379,  0.99018276],
       [-2.20319712, -3.52701815, -2.12533718,  1.31018019, -0.08291182],
       [-0.12889688, -2.77730461, -0.11941056, -2.24005854, -1.78085492]])

In [173]:
sample_array_sqrd

array([[4.03859932e-01, 8.36761670e-01, 3.29612015e-03, 2.77016961e-01,
        2.61986274e-03],
       [6.07697457e-02, 5.10446993e-06, 2.99731768e-03, 1.37939132e-03,
        1.35583694e+00],
       [9.27251621e-01, 7.91154537e-03, 4.57760893e-01, 9.92681817e-01,
        1.34685118e-01],
       [3.30893713e+00, 5.25459555e-03, 9.35710623e-01, 7.63169835e-01,
        3.71424611e+00],
       [1.31824254e+00, 1.21739705e+00, 5.83814277e-01, 9.92288492e-02,
        2.43292377e-01]])

In [174]:
np.round(sample_array_sqrd,2)

array([[0.4 , 0.84, 0.  , 0.28, 0.  ],
       [0.06, 0.  , 0.  , 0.  , 1.36],
       [0.93, 0.01, 0.46, 0.99, 0.13],
       [3.31, 0.01, 0.94, 0.76, 3.71],
       [1.32, 1.22, 0.58, 0.1 , 0.24]])

In [173]:
np.mean(sample_array_sqrd)

0.9609304575806025

In [174]:
np.std(sample_array_sqrd)

1.1551923660289223

In [175]:
np.median(sample_array_sqrd)

0.8551685924630452

In [175]:
items_id_array = np.array(["pen","box","tube","cloth","pen","tube"])

In [176]:
car_names_array = np.array(car_df["car_name"])

In [177]:
car_names_array.shape

(398,)

In [178]:
unique_car_names_array = np.unique(car_names_array)

In [179]:
unique_car_names_array.shape

(305,)

In [180]:
np.in1d(unique_car_names_array,["chevrolet chevelle malibu","ford pinto"])

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

Input and Output

In [181]:
np.save("DSP1220201 - sample_array",sample_array)

In [183]:
np.load("DSP1220201 - sample_array.npy")

array([[ 0.63549975,  0.91474678,  0.05741185, -0.52632401, -0.05118459],
       [ 0.2465152 , -0.00225931,  0.05474776,  0.03714016,  1.16440411],
       [ 0.96293905,  0.08894687, -0.67658029, -0.99633419, -0.36699471],
       [ 1.81904841, -0.07248859, -0.96732136,  0.87359592,  1.92723795],
       [-1.14814744,  1.10335717,  0.7640774 , -0.31500611,  0.49324677]])

In [184]:
np.savetxt("DSP1220201 - sample_array.txt",sample_array)

In [197]:
np.loadtxt("DSP1220201 - sample_array.txt")

array([[ 0.71262681, -0.92475326,  1.02873492, -1.09757247,  0.4106355 ],
       [-0.08582751, -1.06011587, -1.08103404,  0.98859708, -0.42493601],
       [ 0.46322486, -0.09545138,  1.54677332, -2.11490923, -1.64064816],
       [ 0.33233939, -0.1714422 , -0.34553249, -1.92531597,  0.95939163],
       [ 0.93758446,  0.24941121, -0.94204213, -0.32627025, -0.41048025]])

In [185]:
np.savez("DSP1220201 - Zipped",file1=sample_array,file2=sample_array_sqrd)

In [186]:
archived_array = np.load("DSP1220201 - Zipped.npz")

In [187]:
archived_array

In [188]:
archived_array['file1']

array([[ 0.63549975,  0.91474678,  0.05741185, -0.52632401, -0.05118459],
       [ 0.2465152 , -0.00225931,  0.05474776,  0.03714016,  1.16440411],
       [ 0.96293905,  0.08894687, -0.67658029, -0.99633419, -0.36699471],
       [ 1.81904841, -0.07248859, -0.96732136,  0.87359592,  1.92723795],
       [-1.14814744,  1.10335717,  0.7640774 , -0.31500611,  0.49324677]])

In [189]:
archived_array['file2']

array([[4.03859932e-01, 8.36761670e-01, 3.29612015e-03, 2.77016961e-01,
        2.61986274e-03],
       [6.07697457e-02, 5.10446993e-06, 2.99731768e-03, 1.37939132e-03,
        1.35583694e+00],
       [9.27251621e-01, 7.91154537e-03, 4.57760893e-01, 9.92681817e-01,
        1.34685118e-01],
       [3.30893713e+00, 5.25459555e-03, 9.35710623e-01, 7.63169835e-01,
        3.71424611e+00],
       [1.31824254e+00, 1.21739705e+00, 5.83814277e-01, 9.92288492e-02,
        2.43292377e-01]])

In [192]:
np.savetxt("DSP1220201 - Car Names",car_names_array,fmt="%s")

In [195]:
np.loadtxt("DSP1220201 - Car Names",dtype='str',delimiter="*")

array(['chevrolet chevelle malibu', 'buick skylark 320',
       'plymouth satellite', 'amc rebel sst', 'ford torino',
       'ford galaxie 500', 'chevrolet impala', 'plymouth fury iii',
       'pontiac catalina', 'amc ambassador dpl', 'dodge challenger se',
       "plymouth 'cuda 340", 'chevrolet monte carlo',
       'buick estate wagon (sw)', 'toyota corona mark ii',
       'plymouth duster', 'amc hornet', 'ford maverick', 'datsun pl510',
       'volkswagen 1131 deluxe sedan', 'peugeot 504', 'audi 100 ls',
       'saab 99e', 'bmw 2002', 'amc gremlin', 'ford f250', 'chevy c20',
       'dodge d200', 'hi 1200d', 'datsun pl510', 'chevrolet vega 2300',
       'toyota corona', 'ford pinto', 'amc gremlin',
       'plymouth satellite custom', 'chevrolet chevelle malibu',
       'ford torino 500', 'amc matador', 'chevrolet impala',
       'pontiac catalina brougham', 'ford galaxie 500',
       'plymouth fury iii', 'dodge monaco (sw)',
       'ford country squire (sw)', 'pontiac safari (sw)',
 